"""empty message

Revision ID: 333d77eff88b
Revises:
Create Date: 2024-09-18 23:50:31.418852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "333d77eff88b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"buckets",
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column("name", sa.String(), nullable=False),
		sa.Column(
			"created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("name"),
	)
	op.create_table(
		"files",
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column("name", sa.String(), nullable=False),
		sa.Column("mime_type", sa.String(), nullable=True),
		sa.Column("size", sa.Integer(), nullable=False),
		sa.Column("checksum", sa.String(), nullable=False),
		sa.Column("bucket_id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
		),
		sa.ForeignKeyConstraint(
			["bucket_id"],
			["buckets.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("files")
	op.drop_table("buckets")
	# ### end Alembic commands ###
