"""empty message

Revision ID: df338f0cef66
Revises: 4840a2136995
Create Date: 2024-10-06 18:08:07.060737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df338f0cef66"
down_revision: Union[str, None] = "4840a2136995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"files",
		"id",
		existing_type=sa.UUID(),
		type_=sa.String(),
		existing_nullable=False,
	)
	op.drop_constraint("files_name_bucket_id_uc", "files", type_="unique")
	op.drop_column("files", "name")
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"files", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
	)
	op.create_unique_constraint(
		"files_name_bucket_id_uc", "files", ["name", "bucket_id"]
	)
	op.alter_column(
		"files",
		"id",
		existing_type=sa.String(),
		type_=sa.UUID(),
		existing_nullable=False,
	)
	# ### end Alembic commands ###
